# Login user by email and password
# @name login
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail2.ru",
  "password": "123456"
}

###
@authToken = {{login.response.body.access_token}}

# Get gyms by default
GET http://localhost:3333/api/gym?count=3 HTTP/1.1
Authorization: Bearer {{authToken}}
###
