# Create a new user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail2.ru",
  "firstname": "Yuri",
  "avatar": "qwerty",
  "password": "123456",
  "role": "пользователь",
  "dateBirth": "1990-10-24",
  "location": "Спортивная",
  "gender": "мужской",
  "userSurvey": {
    "level": "новичок",
    "type": ["бокс"],
    "time": "30-50 мин",
    "caloriesToLose": 1000,
    "caloriesLosePerDay": 1000,
    "readyToTrain": true
  },
  "coachSurvey": {}
}

###

# Create a new coach
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail1.ru",
  "firstname": "Yuri",
  "avatar": "qwerty",
  "password": "654321",
  "role": "тренер",
  "dateBirth": "1990-10-24",
  "location": "Спортивная",
  "gender": "мужской",
  "userSurvey": {},
  "coachSurvey": {
    "level": "профессионал",
    "type": ["бег", "бокс"],
    "certificate": "asdf",
    "achievements": "Бывший тренер сборной",
    "personalTraining": true
  }
}

###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail1.ru",
  "password": "654321"
}

###
