# Login user by email and password
# @name login
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail2.ru",
  "password": "123456"
}

###
@authToken = {{login.response.body.access_token}}

#Update user
# @name updateUser
PATCH  http://localhost:3333/api/user/update HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "favoriteGym": "642db2d41dee5440e93b06aa"
}

###

# Get user by ID
GET http://localhost:3333/api/user/642db2dc1dee5440e93b06ae HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Get users by default
GET http://localhost:3333/api/user HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Get friends by default
GET http://localhost:3333/api/user/643d4bc0736e974c71711cca/friends HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Update friends list
PATCH http://localhost:3333/api/user/updateFriends/6443a65ec8fad5d9da5cb444?type=add HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Update user balance
PATCH http://localhost:3333/api/user/updateUserBalance?type=link HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "training": "ytrewq"
}
###

# Create subscriber
POST http://localhost:3333/api/user/subscribe/6440349cdcdb0928f8b6f041 HTTP/1.1
Authorization: Bearer {{authToken}}

###


# Get alerts by default
GET http://localhost:3333/api/user/6443a65ec8fad5d9da5cb444/alerts HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Get alert by ID
GET  http://localhost:3333/api/user/alerts/6443a890272bb0a059af3230 HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Delete alert by ID
DELETE http://localhost:3333/api/user/alerts/6443a890272bb0a059af3230 HTTP/1.1
Authorization: Bearer {{authToken}}
###

