# Login user by email and password
# @name login
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail1.ru",
  "password": "123456"
}

###
@authToken = {{login.response.body.access_token}}

#Update user
# @name updateUser
PATCH  http://localhost:3333/api/user/update HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "friend": "642db2d41dee5440e93b06aa"
}

###

# Get user by ID
GET http://localhost:3333/api/user/642db2dc1dee5440e93b06ae HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Get users by default
GET http://localhost:3333/api/user HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Get friends by default
GET http://localhost:3333/api/user/643d4bc0736e974c71711cca/friends HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Update friends list
PATCH http://localhost:3333/api/user/updateFriends/643d514f730694208fa05c03?type=delete HTTP/1.1
Authorization: Bearer {{authToken}}

###
