# Login user by email and password
# @name login
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "ivanov_m@mail.ru",
  "password": "123456"
}

###
@authToken = {{login.response.body.access_token}}

#Update user
PATCH  http://localhost:3333/api/user/update HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "firstname": "Alex"
}

###

#Get favorite gyms
GET http://localhost:3333/api/favorite-gyms HTTP/1.1
Authorization: Bearer {{authToken}}
###

#Update favorite gyms list
PATCH  http://localhost:3333/api/favorite-gyms/update/6447adf8fac4d9d47b8b3c77?type=add HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Get user by ID
GET http://localhost:3333/api/user/642db2dc1dee5440e93b06ae HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Get users by default
GET http://localhost:3333/api/user HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Get friends by default
GET http://localhost:3333/api/friends HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Update friends list
PATCH http://localhost:3333/api/friends/update-friends/645402b28a07a2ce526d0977?type=add HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Update user balance
PATCH http://localhost:3333/api/user/update-user-balance?type=link HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "training": "ytrewq"
}
###

# Create subscriber
POST http://localhost:3333/api/user/subscribe/645402b28a07a2ce526d0977 HTTP/1.1
Authorization: Bearer {{authToken}}

###


# Get alerts by default
GET http://localhost:3333/api/user/6443a65ec8fad5d9da5cb444/alerts HTTP/1.1
Authorization: Bearer {{authToken}}

###

# Get alert by ID
GET  http://localhost:3333/api/user/alerts/6443a890272bb0a059af3230 HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Delete alert by ID
DELETE http://localhost:3333/api/user/alerts/6443a890272bb0a059af3230 HTTP/1.1
Authorization: Bearer {{authToken}}
###

