#Create order
POST http://localhost:3333/api/order/6425c3ce747dae4105fca8e0/6424474c89318b953f242c87/6422bc52eaee6d038e1d863c HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
  "orderType": "тренировка",
  "price": 400,
  "amount": 2,
  "paymentType": "mir",
  "dateBirth": "2022-10-24"
}

###

#Get all orders for coach
GET http://localhost:3333/api/order/6425c3ce747dae4105fca8e0/6422bc52eaee6d038e1d863c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI1YzNjZTc0N2RhZTQxMDVmY2E4ZTAiLCJlbWFpbCI6InVzZXJAbWFpbDEucnUiLCJ1c2VyUm9sZSI6InVzZXIiLCJmaXJzdG5hbWUiOiJNYXgzMjEiLCJpYXQiOjE2ODAxOTc3MDEsImV4cCI6MTY4MDE5Nzc2MX0.y71R3-gJ9077G1VFL4AAcoLx9IiZAt1CLLQnIpKcy1I

###
