# Login user by email and password
# @name login
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail123W.ru",
  "password": "654321"
}

###

@authToken = {{login.response.body.access_token}}

#Create order
POST http://localhost:3333/api/order/642db8d3d7e18e6c2778fd9c HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "orderType": "тренировка",
  "price": 400,
  "amount": 2,
  "paymentType": "mir",
  "dateBirth": "2022-10-24"
}

###

#Get all orders for coach
GET http://localhost:3333/api/order/642db2dc1dee5440e93b06ae HTTP/1.1
Authorization: Bearer {{authToken}}
###
