# Login user by email and password
# @name login
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@mail2.ru",
  "password": "123456"
}

###

@authToken = {{login.response.body.access_token}}

# Create a new food diary
POST http://localhost:3333/api/trainingDiary/create/64397fb09bb44e31ad8a966c HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "caloriesSpentAmount": 155,
  "date": "2021-10-24"
}

###

# Update food diary
PATCH  http://localhost:3333/api/trainingDiary/64399264a418229ca0d9b2d0 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "caloriesSpentAmount": 200
}

###

# Get food diary by ID
GET  http://localhost:3333/api/trainingDiary/64399264a418229ca0d9b2d0 HTTP/1.1
Authorization: Bearer {{authToken}}
###

# Delete food diary by ID
DELETE http://localhost:3333/api/trainingDiary/64399264a418229ca0d9b2d0 HTTP/1.1
Authorization: Bearer {{authToken}}
###
